// <auto-generated />
using System;
using Futoverseny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Futoverseny.Migrations
{
    [DbContext(typeof(VersenyContext))]
    [Migration("20230328063522_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Futoverseny.Data.TavolsagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TavolsagModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "5 km"
                        },
                        new
                        {
                            Id = 2,
                            Name = "10 km"
                        },
                        new
                        {
                            Id = 3,
                            Name = "félmaraton"
                        },
                        new
                        {
                            Id = 4,
                            Name = "maraton"
                        });
                });

            modelBuilder.Entity("Futoverseny.Data.VersenyzoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Korosztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Neme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rajtszam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SzuletesiDatum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TavolsagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Rajtszam")
                        .IsUnique();

                    b.HasIndex("TavolsagId");

                    b.ToTable("Versenyzok");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Korosztaly = "senior",
                            Neme = "ffi",
                            Nev = "Béla",
                            Rajtszam = 5,
                            TavolsagId = 4
                        },
                        new
                        {
                            Id = 2,
                            Korosztaly = "junior",
                            Neme = "nő",
                            Nev = "Tünde",
                            Rajtszam = 7,
                            TavolsagId = 1
                        });
                });

            modelBuilder.Entity("Futoverseny.Data.VersenyzoModel", b =>
                {
                    b.HasOne("Futoverseny.Data.TavolsagModel", "Tavolsag")
                        .WithMany()
                        .HasForeignKey("TavolsagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tavolsag");
                });
#pragma warning restore 612, 618
        }
    }
}
